### ISSUE TITLE
作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！

### ISSUE THREAD

**Issue by Passion-ysh** [hanabi7/VoteHMR#1]

**Comment by hanabi7** [comment]
hello, you can generate gt joints 3d using gt data provided by surreal datasets, smpl_joints3d and gt_joints3d have some divergence but basicly they are the same thing.

**Comment by Passion-ysh** [comment]
谢谢你的答复！！！我理解的是，smpl_joint是完整点云关节，gt_joint是部分点云的（类似于深度图只有单视角），那么后者是在前者基础上取对应部分即可吗？还是说通过预先训练好的网络预测输入部分点云关节？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月17日(周日) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hanabi7/VoteHMR] 作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！ (Issue #1)




 
hello, you can generate gt joints 3d using gt data provided by surreal datasets, smpl_joints3d and gt_joints3d have some divergence but basicly they are the same thing.

**Comment by hanabi7** [comment]
the gt joints provided by surreal dataset contains all the joints position， included the occluded ones，in order to know how to generate joints3d, you can check the paper, surreal learning from synthetic humans



| |
刘冠泽
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月18日 09:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hanabi7/VoteHMR] 作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！ (Issue #1) |

谢谢你的答复！！！我理解的是，smpl_joint是完整点云关节，gt_joint是部分点云的（类似于深度图只有单视角），那么后者是在前者基础上取对应部分即可吗？还是说通过预先训练好的网络预测输入部分点云关节？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月17日(周日) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hanabi7/VoteHMR] 作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！ (Issue #1)





hello, you can generate gt joints 3d using gt data provided by surreal datasets, smpl_joints3d and gt_joints3d have some divergence but basicly they are the same thing.

**Comment by Passion-ysh** [comment]
ok,thanks!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月18日(周一) 上午9:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hanabi7/VoteHMR] 作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！ (Issue #1)




 the gt joints provided by surreal dataset contains all the joints position， included the occluded ones，in order to know how to generate joints3d, you can check the paper, surreal learning from synthetic humans
 
 
 
 | |
 刘冠泽
 |
 |
 ***@***.***
 |
 
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2022年04月18日 09:36 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.******@***.***&gt; |
 | 主题 | Re: [hanabi7/VoteHMR] 作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！ (Issue #1) |
 
 谢谢你的答复！！！我理解的是，smpl_joint是完整点云关节，gt_joint是部分点云的（类似于深度图只有单视角），那么后者是在前者基础上取对应部分即可吗？还是说通过预先训练好的网络预测输入部分点云关节？
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2022年4月17日(周日) 中午12:25
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [hanabi7/VoteHMR] 作者你好，请问下数据gt中的gt_joint3d是深度图点云的关节吗？smpl_joint3d我倒是知道如何获得，但是这个输入点云的joint3d是怎么预先生成的？望告知下，万分感谢！ (Issue #1)
 
 
 
 
 
 hello, you can generate gt joints 3d using gt data provided by surreal datasets, smpl_joints3d and gt_joints3d have some divergence but basicly they are the same thing.
